# from number_datatype import integer
# from number_datatype import realNum
# from number_datatype import round
# from number_datatype import operator
# from list_datatype import list
# from list_datatype import indexing
# from list_datatype import slicing
# from list_datatype import comprehension
# from list_datatype import etc_method
# from string_datatype import string
# from string_datatype import stringOperation
# from tupple_datatype import tupple
# from dictionary_datatype import dictionary
# from set_datatype import set
# from inputoutput import inout
# from inputoutput import varstring
# from ifelifelse import score
# from ifelifelse import andor
# from ifelifelse import conditionalExpress
# from WhileFor import oddNum
# from WhileFor import forContinue
# from WhileFor import whileBreak
# from WhileFor import ex1_for
# from WhileFor import ex2_for
# from FunctionEx import addFunc
from FunctionEx import globalKey
